-- Table rename: device_previews -> DevicePreview
EXEC sp_rename 'dbo.device_previews', 'DevicePreview';
-- Table rename: form_fields -> FormField
EXEC sp_rename 'dbo.form_fields', 'FormField';
-- Table rename: form_submissions -> FormSubmission
EXEC sp_rename 'dbo.form_submissions', 'FormSubmission';
-- Table rename: form_templates -> FormTemplate
EXEC sp_rename 'dbo.form_templates', 'FormTemplate';
-- Table rename: protected_zones -> ProtectedZone
EXEC sp_rename 'dbo.protected_zones', 'ProtectedZone';
EXEC sp_rename 'dbo.GlobalSetting.PK__GlobalSe__0AC8F32298D6B81F', 'PK_GlobalSetting', 'OBJECT';
EXEC sp_rename 'dbo.CanvasObject.PK__CanvasOb__FAD31D5B331536B3', 'PK_CanvasObject', 'OBJECT';
EXEC sp_rename 'dbo.Invitation.PK__Invitati__033C8D2F2B19A232', 'PK_Invitation', 'OBJECT';
EXEC sp_rename 'dbo.TextInputObject.PK__TextInpu__7DBAC9358AE7FFCF', 'PK_TextInputObject', 'OBJECT';
EXEC sp_rename 'dbo.DropdownObject.PK__Dropdown__5FDA92B9329B972F', 'PK_DropdownObject', 'OBJECT';
EXEC sp_rename 'dbo.EmailVerificationToken.PK__EmailVer__3214EC0741580AB6', 'PK_EmailVerificationToken', 'OBJECT';
EXEC sp_rename 'dbo.PasswordResetToken.PK__Password__3214EC0791A1AFC0', 'PK_PasswordResetToken', 'OBJECT';
EXEC sp_rename 'dbo.DropdownOption.PK__Dropdown__315B04D602CA33AF', 'PK_DropdownOption', 'OBJECT';
EXEC sp_rename 'dbo.AuthEvent.PK__AuthEven__920622937C9B7916', 'PK_AuthEvent', 'OBJECT';
EXEC sp_rename 'dbo.ButtonObject.PK__ButtonOb__B0C0392C07A251F1', 'PK_ButtonObject', 'OBJECT';
EXEC sp_rename 'dbo.ProtectedZone.PK__Protecte__5113E33B102BA9EE', 'PK_ProtectedZone', 'OBJECT';
EXEC sp_rename 'dbo.ApplicationLog.PK__Applicat__5E5499A89CCBE779', 'PK_ApplicationLog', 'OBJECT';
EXEC sp_rename 'dbo.AuditLog.PK__AuditLog__A17F23B8479D13D1', 'PK_AuditLog', 'OBJECT';
EXEC sp_rename 'dbo.EventRegistration.PK__EventReg__83225AB27BF0275F', 'PK_EventRegistration', 'OBJECT';
EXEC sp_rename 'dbo.ErrorLog.PK__ErrorLog__358565CA71006DB4', 'PK_ErrorLog', 'OBJECT';
EXEC sp_rename 'dbo.Organization.PK__Organiza__CADB0B724AC4D262', 'PK_Organization', 'OBJECT';
EXEC sp_rename 'dbo.FieldResponse.PK__FieldRes__B94C0F6D73B50ECD', 'PK_FieldResponse', 'OBJECT';
EXEC sp_rename 'dbo.FormBuilderImage.PK__FormBuil__1BF21F84C01DEF2A', 'PK_FormBuilderImage', 'OBJECT';
EXEC sp_rename 'dbo.form_templates.PK__form_tem__3213E83F3C3D10AB', 'PK_form_templates', 'OBJECT';
EXEC sp_rename 'dbo.protected_zones.PK__protecte__3213E83FDC1DC8FE', 'PK_protected_zones', 'OBJECT';
EXEC sp_rename 'dbo.form_fields.PK__form_fie__3213E83F58B6480D', 'PK_form_fields', 'OBJECT';
EXEC sp_rename 'dbo.form_submissions.PK__form_sub__3213E83F1DA0A837', 'PK_form_submissions', 'OBJECT';
EXEC sp_rename 'dbo.device_previews.PK__device_p__3213E83F6A9CBE5C', 'PK_device_previews', 'OBJECT';
EXEC sp_rename 'dbo.SchemaVersion.PK__SchemaVe__3DEF23D9B3D516F6', 'PK_SchemaVersion', 'OBJECT';
EXEC sp_rename 'dbo.Role.PK__Role__8AFACE3A9E1133AB', 'PK_Role', 'OBJECT';
EXEC sp_rename 'dbo.User.PK__User__1788CCAC7AE472DA', 'PK_User', 'OBJECT';
EXEC sp_rename 'dbo.SchemaChangeLog.PK__SchemaCh__7067F0F22DDFA56E', 'PK_SchemaChangeLog', 'OBJECT';
EXEC sp_rename 'dbo.Form.PK__Form__FB05B7BD7DE6F6D1', 'PK_Form', 'OBJECT';
EXEC sp_rename 'dbo.EnvironmentVersion.PK__Environm__5C9D8C8A369D27E9', 'PK_EnvironmentVersion', 'OBJECT';
EXEC sp_rename 'dbo.Event.PK__Event__7944C870DBD01DDC', 'PK_Event', 'OBJECT';
EXEC sp_rename 'dbo.UsageCharge.PK__UsageCha__0E0249A6A895A4E8', 'PK_UsageCharge', 'OBJECT';
EXEC sp_rename 'dbo.Canvas.PK__Canvas__9F4D1A4C5530C77B', 'PK_Canvas', 'OBJECT';
EXEC sp_rename 'dbo.UserRole.PK__UserRole__AF27604F8230705C', 'PK_UserRole', 'OBJECT';
EXEC sp_rename 'dbo.EventDayEntitlement.PK__EventDay__F859017BAE82D020', 'PK_EventDayEntitlement', 'OBJECT';
EXEC sp_rename 'dbo.CanvasLayout.PK__CanvasLa__BEF7D0D6D4D93382', 'PK_CanvasLayout', 'OBJECT';
EXEC sp_rename 'dbo.ObjectType.PK__ObjectTy__D9A48E9CDC4E1881', 'PK_ObjectType', 'OBJECT';
EXEC sp_rename 'dbo.UsageCharge.FK__UsageChar__Organ__6E2152BE', 'FK_UsageCharge_Organization', 'OBJECT';
EXEC sp_rename 'dbo.Canvas.FK_Canvas_BackgroundImage', 'FK_Canvas_FormBuilderImage', 'OBJECT';
EXEC sp_rename 'dbo.protected_zones.FK__protected__form___4F7CD00D', 'FK_protected_zones_form_templates', 'OBJECT';
EXEC sp_rename 'dbo.form_fields.FK__form_fiel__form___52593CB8', 'FK_form_fields_form_templates', 'OBJECT';
EXEC sp_rename 'dbo.form_submissions.FK__form_subm__form___5535A963', 'FK_form_submissions_form_templates', 'OBJECT';
EXEC sp_rename 'dbo.device_previews.FK__device_pr__form___5812160E', 'FK_device_previews_form_templates', 'OBJECT';
EXEC sp_rename 'dbo.EmailVerificationToken.FK__EmailVeri__UserI__1E6F845E', 'FK_EmailVerificationToken_User', 'OBJECT';
EXEC sp_rename 'dbo.PasswordResetToken.FK__PasswordR__UserI__22401542', 'FK_PasswordResetToken_User', 'OBJECT';
EXEC sp_rename 'dbo.Event.FK_Event_CreatedByUser', 'FK_Event_User', 'OBJECT';
EXEC sp_rename 'dbo.Canvas.FK_Canvas_CreatedByUser', 'FK_Canvas_User', 'OBJECT';
EXEC sp_rename 'dbo.Form.FK__Form__EventID__68687968', 'FK_Form_Event', 'OBJECT';
EXEC sp_rename 'dbo.UsageCharge.FK__UsageChar__Event__6F1576F7', 'FK_UsageCharge_Event', 'OBJECT';
EXEC sp_rename 'dbo.form_templates.ix_form_templates_id', 'IX_ix_form_templates_id', 'INDEX';
EXEC sp_rename 'dbo.protected_zones.ix_protected_zones_id', 'IX_ix_protected_zones_id', 'INDEX';
EXEC sp_rename 'dbo.form_fields.ix_form_fields_id', 'IX_ix_form_fields_id', 'INDEX';
EXEC sp_rename 'dbo.form_submissions.ix_form_submissions_id', 'IX_ix_form_submissions_id', 'INDEX';
EXEC sp_rename 'dbo.device_previews.ix_device_previews_id', 'IX_ix_device_previews_id', 'INDEX';
EXEC sp_rename 'dbo.EventDayEntitlement.IDX_EventDayEntitlement_Event_Date', 'IX_IDX_EventDayEntitlement_Event_Date', 'INDEX';