openapi: 3.0.3
info:
  title: Metering Ingest API
  version: 0.1.1
paths:
  /metering/events:
    post:
      summary: Enqueue metering events (batch)
      operationId: createMeteringEvents
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                type: object
                required: [request_id, sku, quantity, org_id, project_id, time]
                properties:
                  request_id:
                    type: string
                  sku:
                    type: string
                  quantity:
                    type: number
                  org_id:
                    type: string
                  project_id:
                    type: string
                  time:
                    type: string
                    format: date-time
      responses:
        '202':
          description: Accepted for processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  accepted:
                    type: integer
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '409':
          description: Duplicate request_id (idempotent)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        code:
          type: string
        request_id:
          type: string
