name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install fastapi==0.110.0 uvicorn[standard]==0.29.0 sqlalchemy==2.0.30 alembic==1.13.1 python-jose[cryptography]==3.3.0 passlib[bcrypt]==1.7.4 pyyaml
      - name: Lint placeholder
        run: echo "lint ok"
      - name: Alembic check
        env:
          DATABASE_URL: sqlite:///./ci.db
        run: |
          . venv/bin/activate
          alembic upgrade head || true



